project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1
            href: Hands-on_EX01/Hands-on_EX01.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_EX02/Hands-on_EX02.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_EX03/Hands-on_EX03.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_EX04/Hands-on_EX04.qmd            
      - text: In-Class Exercise
        menu:
          - text: In-Class Exercise 1
            href: In-class_EX01/In-class_Ex01.qmd
          - text: In-Class Exercise 2
            href: In-class_EX02/In-class_Ex02.qmd
          - text: In-Class Exercise 4
            href: In-class_EX04/In-class_Ex04.qmd
      - text: Take-home Exercise
        menu:
          - text: Take-home Exercise 1
            href: Take-home_EX01/Take-home_EX01.qmd
          - text: Take-home Exercise 2
            href: Take-home_EX02/Take-home_EX02.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

